### ISSUE TITLE
Уменьшить вес ещё больше

### ISSUE THREAD

**Issue by Otorhin** [b3rg3n/mnd#1]
Можно сократить вес ещё в разы. Сделав одну простую вещь. А именно ogv -> webm

**Comment by b3rg3n** [comment]
> Можно сократить вес ещё в разы. Сделав одну простую вещь. А именно ogv -> webm

Конвертер подкинешь? Movavi лишь пятикратно увеличить размер предлагал

**Comment by Otorhin** [comment]
https://github.com/b3rg3n/mnd/commit/10b74bd0abb00b133838d005b7aed5dd05350788
